name: 'Terraform Destroy'

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: production  # Optional: add approval step (see below)

    steps:
    # 1. Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

    # 3. Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 4. Terraform Init
    - name: Terraform Init
      run: terraform init

    # 5. Terraform Destroy (with confirmation)
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
